config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'

  get '/about' => 'static_pages#about'

  resources :categories
  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord

validates :name, presence: true
validates_uniqueness_of :name, case_sensitive: false
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category created'
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def show
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = 'Category updated'
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:success] = 'Category destroyed'
      redirect_to categories_path
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'Post created'
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = 'Post updated'
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:success] = 'Post destroyed'
      redirect_to posts_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @posts = Post.all.order('created_at DESC')
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def about_contact_info_links
    link_text = ''
    link_text += mail_to('ablamunets002@gmail.com', 'Email', class: 'social-media-links') + ', '
    link_text += link_to('Twitter', 'http://Twitter.com/ablamunetsand', class: 'social-media-links') + ', '
    link_text += link_to('Instagram', 'http://instagram.com/ablamunetsand', class: 'social-media-links') + ', '
    link_text += link_to('Facebook', 'http://facebook.com/ablamunets', class: 'social-media-links') + '.'
    link_text.html_safe
  end
end

app/views/categories/_category.html.haml
%tr
  %td
    = link_to category.name, edit_category_path(category)

app/views/categories/_form.html.haml
= form_for @category do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .row
    .col-md-6
      .form-group
        = f.submit 'Save', class: 'btn btn-green align-left'

    .col-md-6
      = link_to 'Delete Category', category_path(@category), method: :delete, data: { confirm: 'Are you sure you want to delte this category?' }, class: 'btn btn-danger align-right' unless @category.new_record?

app/views/categories/edit.html.haml
%h1
  = @category.name
= render 'form'

app/views/categories/index.html.haml
.row
  .col-md-10
    %h1 Categories
  .col-md-2
    = link_to 'Create Category', new_category_path, class: 'btn btn-green align-right'
%table.table.table-hover
  %thead
    %tr
      %th Name
  %tbody
    = render partial: 'category', collection: @categories

app/views/categories/new.html.haml
%h1 Create Category
.well
  = render 'form'

app/views/categories/show.html.haml
%h1
  = @category.name

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Andrey Ablamunets
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.ico'
  %body
    = render template: 'shared/navbar'
    .container-fluid#main-content
      .row
        .col-md-10.col-md-offset-1
          - flash.each do |key, value|
            = content_tag :div, value, class: "alert alert-#{key}"
          = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :body, 'Content'
    = f.text_area :body, id: 'editor', class: 'form-control'

  .row
    .col-md-6
      .form-group
        = f.submit 'Save', class: 'btn btn-green align-left'

    .col-md-6
      = link_to 'Delete Post', post_path(@post), method: :delete, data: { confirm: 'Are you sure you want to delte this category?' }, class: 'btn btn-danger align-right' unless @post.new_record?

:javascript
  $('#editor').froalaEditor({
    inlineMode: false,
    heightMin: '200px',
    toolbarButtons: ['fullscreen', 'bold', 'italic', 'underline', 'strikeThrough',
                     'subscript', 'superscript', 'fontFamily', 'fontSize', '|', 'color',
                     'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat',
                     'align', 'formatOL', 'formatUL', 'outdent', 'indent', '-',
                     'insertLink', 'insertImage', 'insertVideo', 'insertTable', '|', 'quote',
                     'insertHR', 'undo', 'redo', 'clearFormatting', 'selectAll', 'html'],
  })

app/views/posts/_post.html.haml
%tr
  %td
    = link_to post.title, edit_post_path(post)

app/views/posts/edit.html.haml
%h1
  = @post.title
= render 'form'

app/views/posts/index.html.haml
.row
  .col-md-10
    %h1 Posts
  .col-md-2
    = link_to 'Create Post', new_post_path, class: 'btn btn-green align-right'
%table.table.table-hover
  %thead
    %tr
      %th Title
  %tbody
    = render partial: 'post', collection: @posts

app/views/posts/new.html.haml
%h1 New Post
.well
  = render 'form'

app/views/posts/show.html.haml
%h1
  = @post.title

.froala-view
  = @post.body.html_safe

app/views/shared/navbar.html.haml
.container-fluid#nav-container
  %nav.navbar.brand-seagreen
    .row
      .col-md-10.col-md-offset-1
        %ul.nav.navbar-nav
          %li
            = link_to 'HOME', root_path
          %li
            = link_to 'RUNNING DISCOUNT CODES', href: '#'
          %li
            = link_to 'ABOUT ME', about_path
          - if user_signed_in? && current_user.internal?
            %li
              = link_to 'CATEGORIES', categories_path
            %li
              = link_to 'MANAGE POSTS', posts_path
        #main-nav-collapse.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li
                = link_to "My Profile", edit_user_registration_path
              %li
                = button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger navbar-button'
            - else
              = link_to "Log In", new_user_session_path, class: 'btn btn-green navbar-button'





.jumbotron#nav-banner
  %h1 ANDREY ABLAMUNETS
  %p RUNNING THE WORLD

app/views/shared/sidebar.html.haml
.col-md-5.col-md-offset-1
  .well#sidebar-container
    %h3 FOLLOW MY BLOG
    %p Enter your email address to follow this blog and receive notifications of new posts by email.

    %input{ type: 'text', name: 'email', placeholder: 'Enter your email address', id: 'subscribe-field' }
    %input{ type: 'submit', value: 'FOLLOW', class: 'btn btn-green'}

  .well#sidebar-container
    %h3 FIND ME ON SOCIAL MEDIA
    .sidebar-sm-icons
      %a{href: "https://www.facebook.com/facebook.com/ablamunets", title: "facebook"}
        %i.fa.fa-facebook-official.fa-2x{style: "margin-right: 0.5em; color: #d12d00;"}
      %a{href: "https://twitter.com/twitter.com/ablamunetsand", title: "twitter"}
        %i.fa.fa-twitter.fa-2x{style: "margin-right: 0.5em; color: #d12d00;"}
      %a{href: "https://instagram.com/ablamunetsand", title: "instagram"}
        %i.fa.fa-instagram.fa-2x{style: "margin-right: 0.5em; color: #d12d00;"}
      %a{href: "https://www.youtube.com/channel/UCNmSPhSCbzWb0oVUJcXrNHQ", title: "instagram"}
        %i.fa.fa-youtube-play.fa-2x{style: "margin-right: 0.5em; color: #d12d00;"}

  .well#sidebar-container
    %h3 INSTAGRAM

  .well#sidebar-container
    %h3 TWITTER MACHINE
    %a.twitter-timeline{href: "https://twitter.com/AblamunetsAnd", 'data-tweet-limit' => '3' }
    %script{:async => "", :charset => "utf-8", :src => "//platform.twitter.com/widgets.js"}


  .well#sidebar-container
    = image_tag('bib-rave-circle-badge.jpg')

  .well#sidebar-container
    %h3 ANDREY'S BLOG

  .well#sidebar-container
    %h3
      - if user_signed_in? && current_user.internal?
        = link_to 'CATEGORIES', categories_path
      - else
        CATEGORIES
    %h4
      %ul.unstyle-list
        - Category.all.each do |category|
          %li
            %a{href: category_path(category), title: "#{category.name}"}
              %i.fa.fa-folder-open.fa-1x{style: "color: #d12d00;"}
                = category.name

app/views/static_pages/about.html.haml
.col-md-6
  %h1 About Me
  %br
  %p Welcome!
  %br
  %p I am excited to share my perspective on running and traveling with you! I have been running for over 10 years now, mostly on recreational level, but in the past 2 years I have take the sport a lot more seriously. I have ran everything from 400m, in college, to marathons. I have worked with some amazing coaches and runners and have gained good experience with training, nutrition,  racing and recovery. I love to run, share my experience, and provide a little inspiration.
  %br
  %p Besides running, I love to travel and experience new cultures, food, and adventures. I try to never say “no” to a new opportunity or experience. I have lived in Russia and Australia, and now I am located in beautiful Minneapolis, MN. I plan on taking my love for running on the road and sharing my experience.
  %br
  %p Besides running, I stay active by Mountain Biking and Volleyball. I love to stay active and more importantly stay outdoors. I want to be able to connect and collaborate with runners and travelers.
  %br
  %p
    Come on a run with me:
    = about_contact_info_links
= render template: 'shared/sidebar'

app/views/static_pages/home.html.haml
.col-md-6
  - if @posts.any?
    - @posts.each do |post|
      .post-container
        %h2
          = post.title

        = post.body.html_safe
  - else
    %h3 There are currently no posts!
= render template: 'shared/sidebar'